// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $StoreMap from "./islands/StoreMap.tsx";
import * as $StorePageCep from "./islands/StorePageCep.tsx";
import * as $StorePageContainer from "./islands/StorePageContainer.tsx";
import * as $StorePageMapList from "./islands/StorePageMapList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/StoreMap.tsx": $StoreMap,
    "./islands/StorePageCep.tsx": $StorePageCep,
    "./islands/StorePageContainer.tsx": $StorePageContainer,
    "./islands/StorePageMapList.tsx": $StorePageMapList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
